name: workflow1
on:
  push:
    branches:
    - main
  workflow_dispatch:
  schedule:
    - cron: "45 * * * 1-5"
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Just want to say hello!"
      - name: task 1 for printing OS details
        run: uname -a
      - name: task 2 for printing hostname
        run: hostname
