name: main
on:
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build-job:
    runs-on: ron-do
    steps:
      - name: Say hello
        run: echo "Just want to say hello!"
      - name: task 1 for printing OS details
        run: uname -a
      - name: task 2 for printing hostname
        run: hostname
      - name: task 3 sleep 30 seconds
        run: sleep 30
      - name: task 4 write completed
        run: |
          echo "Task 4 of build-job complete"
          touch /tmp/rontemp
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Just want to say hello!"
      - name: task 1 for printing OS details
        run: uname -a
      - name: task 2 for printing hostname
        run: hostname
      - name: task 3 sleep 30 seconds
        run: sleep 30
      - name: task 4 write completed
        run: echo "Task 4 of test-job complete"
