name: workflow3
on: 
  push:
    branches:
      - main
jobs:
  build:
     runs-on: ubuntu-latest
     steps:
       - name: step1
         continue-on-error: true
         run: |
           eccho "test step 1 in build"
           sleep 10
  test:
     runs-on: ubuntu-latest
     if: ${{ needs.build.result == 'failure' }}
     steps:
       - name: step1
         run: |
           echo "test step 1 in test"
           sleep 10    
  test2:
     runs-on: ubuntu-latest
     needs: [ build,build2 ]
     steps:
       - name: step1
         run: |
           echo "test step 1in test 2"
           sleep 10
  build2:
     runs-on: ubuntu-latest
     steps:
       - name: step1
         run: |
           echo "test step 1 in build 2"
           sleep 10    
  deploy:
     runs-on: ubuntu-latest
     if: ${{ always () }}
     steps:
       - name: step1
         run: |
           echo "test step 1 in deploy"
           sleep 10
     needs: test
